---
#- name: Create new server instances and attaches them a network and passes metadata to the instance
- name: Gather facts about previously created networks
  os_networks_facts:
    cloud: ospcloud
- name: show network details
  debug:
    var: openstack_networks

- name: Gather facts about previously created subnets
  os_subnets_info:
    cloud: ospcloud

- name: show subnet details
  debug:
    var: openstack_subnets
#- name: Add floating IP to Servers
   

#- name: Wait for server to be available
