---
#- name: check the code to extract
#  debug:
#    msg: "name={{ item.value.name }} meta={{ item.value.meta }}"
#  with_dict: "{{osp_servers}}"

#- name: Create new server instances and attaches them a network and passes metadata to the instance
#- name: Gather facts about previously created networks
#  os_networks_facts:
#    cloud: ospcloud
#- name: show network details
#  debug:
#    var: openstack_networks
#
#- name: Gather facts about previously created subnets
#  os_subnets_info:
#    cloud: ospcloud
#
#- name: show subnet details
#  debug:
#    var: openstack_subnets
# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    cloud: ospcloud
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    nics:
      - net-name: int_network
    meta: "{{ item.value.name }}"
  with_dict: "{{osp_servers}}"
#
- name: Add floating IP to Servers
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ item.value.name }}"
    network: ext_net
    wait: true
    timeout: 180
  with_dict: "{{osp_servers}}"

  

#- name: Wait for server to be available
